title: ELITMa â€“ ELIXIR Training Programme in Management
# This appears in the html browser tab for the site title (seen mostly by search engines, not users)

topnav_title: ELITMa
# Optional: this appears on the top navigation bar next to the main_logo.svg icon

description: "ELIXIR Training Programme in Management, supporting the planning and delivery of Node activities such as coordination, training, service provision, infrastructure management, events and communication."
# Metadata description of the website

remote_theme: ELIXIR-Belgium/elixir-toolkit-theme

url: "https://elixir-europe-training.github.io"
baseurl: "/ELIXIR-ELITMa"

exclude:
  - README.md
  - vendor
  - Gemfile

sass:
  style: compressed
  sourcemap: never

theme_variables:
  topnav:
    brand_logo: assets/img/main-logo-horizontal.svg
    theme: light
  fonts:
    - https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Source+Serif+4:ital,opsz,wght@0,8..60,200..900;1,8..60,200..900&family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap

topnav_banner: 
# Optional: a banner message to display to users on all pages

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      permalink: /:basename
      layout: "page"
      search_exclude: false
  -
    scope:
      path: "pages/about"
    values:
      sidebar: about
  -
    scope:
      path: "pages/modules/data-management"
    values:
      sidebar: module-data-management
      type_img: /icons/icon-module-data-management.svg
  -
    scope:
      path: "pages/modules/communication"
    values:
      sidebar: module-communication
      type_img: /icons/icon-module-communication.svg


plugins:
  - elixir-toolkit-theme-plugins
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji
  - webrick
